name: Build make for Windows (x86_64)

on:
  workflow_dispatch:
  push:
    branches: [ "main", "feat/deterministic-builds" ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: registry.fedoraproject.org/fedora:40
    steps:
      - name: Install Dependencies
        run: dnf install -y -q mingw64-gcc make wget tar
        
      - uses: actions/checkout@v4

      - name: Download make release tar.gz file
        run: wget "https://ftpmirror.gnu.org/make/$(cat build_version.sha256sum | cut -d ' ' -f3)"
        
      - name: Verify the hash of the tar.gz file
        run: sha256sum -c build_version.sha256sum

      - name: Run the build process
        run: ./cross_build_w64.sh
        
      - name: Hash the built binaries
        run: sha256sum make-*/dist/*
      
      - uses: actions/upload-artifact@v4
        with:
          name: make-bin-win64
          path: ./make-*/dist/
